image: tmaier/docker-compose:18

services:
  - docker:dind

stages:
  - build
  - test
  - package

# before_script:
#   - apk add --no-cache bash

build:
  stage: build
  script:
    - exit 0
  # artifacts:
  #   paths:
  #     - output/summon-conjur-linux-amd64

test-unit:
  stage: test
  script:
    - exit 0
  # artifacts:
  #   paths:
  #     - output/junit.xml

package-tarballs:
  stage: package
  script:
    - exit 0
  # artifacts:
  #   paths:
  #     - output/dist/*
