image:
  name: lachlanevenson/k8s-helm:v2.9.1
  entrypoint: [""]

stages:
  - test
  - package

test-unit:
  stage: test
  script:
    - helm lint --set dataKey=BLOB ./conjur-oss
    # - helm install --set dataKey=BLOB --debug --dry-run ./conjur-oss

package-tarballs:
  stage: package
  script:
    - mkdir -p output
    - helm package --save=false --destination ./output ./conjur-oss
  artifacts:
    paths:
      - output/*.tgz
