image:
  name: lachlanevenson/k8s-helm:v2.9.1
  entrypoint: [""]

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375/  # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
  DOCKER_DRIVER: overlay2

stages:
  - test
  - package

before_script:
  - apk add --no-cache bash docker
  - docker info

test-lint:
  stage: test
  script:
    - helm lint --set dataKey=BLOB ./conjur-oss
  tags:
    - kubernetes

test-integration:
  stage: test
  script:
    - ./test.sh
  tags:
    - kubernetes

package-tarballs:
  stage: package
  script:
    - mkdir -p output
    - helm package --save=false --destination ./output ./conjur-oss
  artifacts:
    paths:
      - output/*.tgz
  tags:
    - kubernetes
