---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-conjur-data-key
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  key: "{{ required "'dataKey' has no value, it must be provided!" .Values.dataKey | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-conjur-database-url
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.databaseUrl }}
  key: {{ .Values.databaseUrl | b64enc }}
  {{ else }}
  key: {{ printf "postgres://postgres@%v-postgres/postgres" .Release.Name | b64enc }}
  {{ end }}
